project:
  type: website

website:
  title: nordatlantisk-ft
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://mtwente.github.io/nordatlantisk-ft/
  repo-url: https://github.com/mtwente/nordatlantisk-ft/
  issue-url: https://github.com/mtwente/nordatlantisk-ft/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: nordatlantisk-ft
    tools:
      - icon: github
        url: https://github.com/mtwente/nordatlantisk-ft/
    left:
      - text: Data Overview
        href: report.qmd
      - text: Codebook
        href: docs/codebook.qmd
      - text: Bibliography
        href: https://www.zotero.org/groups/5346749/nordatlantisk-ft

  sidebar:
    contents:
      - section: nordatlantisk-ft
        href: index.qmd
        contents:
          - text: Changelog
            href: CHANGELOG.md
          - text: Code of Conduct
            href: CODE_OF_CONDUCT.md
          - text: Contributing
            href: CONTRIBUTING.md
          - text: License (Data)
            href: LICENSE-CCBY.md
          - text: License (Code)
            href: LICENSE-AGPL.md
          - text: Security
            href: SECURITY.md
      - href: report.md
        contents: project-management/*

format:
  html:
    toc: true
    theme:
      - brand
      - cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true

freeze: true

editor: visual
