contact_links:
  - name: Are you looking for documentation on nordatlantisk-ft?
    url: https://mtwente.github.io/nordatlantisk-ft
    about: Please see the documentation for nordatlantisk-ft on its GitHub Pages page.
  - name: Do want to discuss nordatlantisk-ft with the community?
    url: https://github.com/mtwente/nordatlantisk-ft/discussions
    about: Please see the discussions page for nordatlantisk-ft.
blank_issues_enabled: true
